async page => {
  await page.setViewportSize({width:1440,height:900});
  await page.goto('http://127.0.0.1:4173/post/12.html');
  const source=page.locator('#postBody img').first();
  await source.scrollIntoViewIfNeeded();
  const scrollBefore=await page.evaluate(()=>scrollY);
  await source.click();
  await page.locator('.gv-image:visible').waitFor();
  const geometry=await page.evaluate(()=>({viewport:innerWidth,dialog:document.querySelector('.gitiu-viewer').getBoundingClientRect().width,locked:document.documentElement.style.overflow}));
  if(geometry.dialog!==geometry.viewport || geometry.locked!=='hidden')throw Error(JSON.stringify(geometry));
  await page.getByRole('button',{name:'放大',exact:true}).click();
  await page.getByRole('button',{name:'放大',exact:true}).click();
  const box=await page.locator('.gv-canvas').boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);
  await page.mouse.down();await page.mouse.move(box.x+box.width/2+100,box.y+box.height/2+80,{steps:5});await page.mouse.up();
  const pan=await page.evaluate(()=>({scale:gitiuLightbox.scale,x:gitiuLightbox.x,y:gitiuLightbox.y}));
  if(pan.scale<=1 || !pan.x || !pan.y)throw Error('Pan failed '+JSON.stringify(pan));
  await page.getByRole('button',{name:'适应窗口',exact:true}).click();
  await page.getByRole('button',{name:'下一张图片',exact:true}).click();
  await page.waitForFunction(()=>gitiuLightbox.index===1 && !gitiuLightbox.image.hidden);
  await page.getByRole('button',{name:'查看第 3 张图片',exact:true}).click();
  await page.waitForFunction(()=>gitiuLightbox.index===2 && !gitiuLightbox.image.hidden);
  await page.waitForFunction(()=>{const r=gitiuLightbox.image.getBoundingClientRect();return r.height>r.width;});
  const portrait=await page.locator('.gv-image').boundingBox();
  if(portrait.height<=portrait.width)throw Error('Portrait aspect changed');
  if(!await page.getByRole('button',{name:'下一张图片',exact:true}).isDisabled())throw Error('Boundary not disabled');
  await page.keyboard.press('ArrowLeft');
  await page.waitForFunction(()=>gitiuLightbox.index===1);
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!gitiuLightbox.dialog.open && document.documentElement.style.overflow!=='hidden');
  const restored=await page.evaluate(()=>({scroll:scrollY,focus:document.activeElement===gitiuLightbox.returnFocus}));
  if(Math.abs(restored.scroll-scrollBefore)>1 || !restored.focus)throw Error('Restore failed '+JSON.stringify(restored));
  await page.setViewportSize({width:390,height:844});
  await source.click();await page.locator('.gv-image:visible').waitFor();
  await page.screenshot({path:'output/playwright/lightbox-final-mobile.png'});
  const cdp=await page.context().newCDPSession(page);
  await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:2});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:145,y:400,id:1},{x:245,y:400,id:2}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:105,y:400,id:1},{x:285,y:400,id:2}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  const pinch=await page.evaluate(()=>gitiuLightbox.scale);
  if(pinch<1.5)throw Error('Pinch failed '+pinch);
  await page.getByRole('button',{name:'适应窗口',exact:true}).click();
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:290,y:400,id:1}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:90,y:400,id:1}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await page.waitForFunction(()=>gitiuLightbox.index===1);
  await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:false});
  await cdp.detach();
  await page.getByRole('button',{name:'关闭图片',exact:true}).click();
  // A broken single-photo article gets a retry, without stale images or gallery arrows.
  const valid=await source.getAttribute('src');
  await page.evaluate(()=>{
    const images=[...document.querySelectorAll('#postBody img')];images.slice(1).forEach(img=>img.remove());
    images[0].src='/missing-lightbox-test.png';delete images[0].dataset.fullSrc;
  });
  await source.click();
  await page.getByRole('button',{name:'重新加载',exact:true}).waitFor();
  if(await page.locator('.gv-thumbs').isVisible())throw Error('Single-image thumbnails visible');
  await source.evaluate((img,url)=>img.src=url,valid);
  await page.getByRole('button',{name:'重新加载',exact:true}).click();
  await page.locator('.gv-image:visible').waitFor();
  await page.keyboard.press('Escape');
  return {geometry,pan,portrait:true,restored,pinch,swipe:true,singleAndRetry:true};
}
